### ISSUE TITLE
Inconsistent offsets of multi EmuNANDs (for some SDs?)

### ISSUE THREAD

**Issue by d0k3** [DarkMatterCore/3ds-multinand#2]
Originally opened as a GM9 issue. GM9 failed to recognize the offset of the second EmuNAND because it wasn't at the expected location. Seems to be specific to certain SD cards, there's no trouble with most and the offset is at the location GM9 expects (there would be a lot more similar issues otherwise).

Multi EmuNAND of course created with 3DS Multi EmuNAND Creator :^)

Link to the original issue: 
https://github.com/d0k3/GodMode9/issues/391

@MrTSXV @DarkMatterCore - please continue sorting this out here, this is a 3DS Multi EmuNAND Creator issue rather than a GM9 issue. I'll try to help and will keep an eye on this issue.

**Comment by DarkMatterCore** [comment]
@MrTSXV Have you been able to test the debug build?

**Comment by d0k3** [comment]
@DarkMatterCore - I fear @MrTSXV has been mia for a long time. Is there anything I can do to help?

As far as I see it, the problem is, this happened on a specific SD card @MrTSXV had, and it's not reproducible on other SD cards.

**Comment by DarkMatterCore** [comment]
I haven't been able to reproduce this error in any of my SD cards (SanDisk 32 GB x 2 / SanDisk 8 GB x 2 / Kingston 4 GB x 1). I'd really like to see the results from the test build in order to track down the bug and close this issue.

@MrTSXV You still around here, bud?

**Comment by d0k3** [comment]
Ugh, long open, unsolvable issues. The pain of Github.

Anyways, @DarkMatterCore - you tried with three SD cards, couldn't reproduce the issue. There never was a similar bug report.

Of course, EmuNAND and RedNAND are not as much in use nowadays as they have been in the past. Still, I think it would be legitimate to close this issue as unsolvable edge case. Maybe even user error, though I doubt that here. Maybe just wait for @MrTSXV for a few days, then close it if there's no further information from him?

**Comment by DarkMatterCore** [comment]
@d0k3 That's exactly what I'm thinking. I'll close this issue if we reach February without an answer from him.

**Comment by DarkMatterCore** [comment]
Alright, so, we reached February and still got no answer from @MrTSXV. I'm closing this issue.

If it ever appears again, I'll gladly research into this matter once again (given enough debug info). Just give me a shout.
